### ISSUE TITLE
Python-3 only todo list

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#292]
### Code
- [ ] run monkeytype to get type annotations everywhere
- [ ] add `__doc__` to namedtuples
- [x] replace `**kwargs` hackery in `@command` with true kwarg
- [ ] grep for python2
- [ ] double check dict. iteration
- [x] replace errno.* with the real exceptions
- [x] replace twisted `returnValue()` with `return`

### setup.py

- [x] use python3
- [x] set the python version with `python_requires`

### Modules

- [x] use `unittest.mock` instead of `mock`
- [x] remove `six`
- [x] check for any other backported modules

### Misc

- [x] remove from CI

Feel free to add to this. This is an issue so that it can easily be closed in one issue by the person doing it.

**Comment by NotAFile** [comment]
good enough
