### ISSUE TITLE
Configuration TODO list

### ISSUE THREAD

**Issue by swalladge** [piqueserver/piqueserver#324]
Quick meta list of major things to be done relating to the config (now that the large new config pr has been merged).

- [x] document all config options in example config, including defaults if left out, allowed values, required options, etc.
- [ ] review and finalize layout of options (some have changed since the last release)
- [ ] create a config porting script - users should be able to `piqueserver --port-config oldconfig.json newconfig.toml`.
- [ ] add validation functions to all config options
- [x] add info to sphinx docs about configuring (toml vs json, the example config, etc.)

**Comment by godwhoa** [comment]
> document all config options in example config, including defaults if left out, allowed values, required options, etc.

Can we document config options(core) in docs. instead of comments?
Already done it for script options: https://piqueserver.readthedocs.io/en/latest/script-options.html

**Comment by swalladge** [comment]
@godwhoa both would be good. :+1:

**Comment by NotAFile** [comment]
if we wanted to over-engineer this, we could have some kind of parsable description we generate both from.

**Comment by NotAFile** [comment]
I have now written a bunch of the documentation stuff. Would be nice if you could give some opinions on it.

**Comment by NotAFile** [comment]
I think we have enough validation and are happy enough with the layout for now?

Porting script is not a useful use of our time IMO, as most installs of piqueserver are already on the TOML version, and it is easy to manually transfer your options over.

Closing, but feel free to object if you disagree.
