### ISSUE TITLE
Extensions Meta-issue

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#499]
A few things need to happen for extensions to become a thing:

 - [x] send and recieve the extension exchange packet
 - [ ] allow specifying what extensions the server uses and what to do when the client doesn't support them
 - [ ] allow declaring the existance of an extension
 - [ ] allow adding contained packet loaders to the extension
 - [ ] add a router/handler for extension packets
 - [ ] allow sending extension packets
